version: '3.8'  # Adicione a versão do compose
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public  # Adiciona a variável de ambiente

  mongo:
    image: mongo
    ports:
      - "27017:27017"
